import './globals.scss';
import { Noto_Sans_JP } from "@next/font/google";
import React from 'react';
import Header from "./components/layers/Header";
import Footer from "./components/layers/Footer";

const notojp = Noto_Sans_JP({
  weight: '500', // あなたが必要とするウェイトを指定します
  subsets: ['latin'], // 必要なサブセットを指定します
  display: 'swap', // フォントの表示方法を指定します
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${notojp.className}`+" tracking-widest"}>
        <Header></Header>
        {children}
        <Footer></Footer>
      </body>
    </html>
  )
}