import './globals.scss'
import { Sawarabi_Gothic } from "next/font/google"
import React from 'react'
import Header from "./components/layers/Header"
import Footer from "./components/layers/Footer"

const Sawarabi = Sawarabi_Gothic({
  weight: "400",
  display: "swap",
  preload: false,
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={Sawarabi.className}>
        <Header></Header>
        {children}
        <Footer></Footer>
      </body>
    </html>
  )
}